.pages: &pages
  image: monachus/hugo
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
     - git status
     - pushd content
     - git pull origin master
     - git status
     - popd
     - hugo
  artifacts:
    paths:
      - public
    expire_in: 10m


test pages:
  <<: *pages
  except:
   - master


# Seperated otherwise merge requests would 
# replace the real site
pages:
  <<: *pages
  only:
   - master
