image: monachus/hugo


variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
  - git status
  - git submodule foreach git pull origin master
  - pushd content
  - git status
  - popd
  - hugo
  artifacts:
    paths:
    - public
    expire_in: 10m
  only:
  - master
