stages:
   - check
   - pages

check if build required:
  stage: check
  image:
    name: alpine/git
    entrypoint: [""]
  variables:
    GIT_STRATEGY: none
    GIT_URL: https://git.card10.badge.events.ccc.de/card10/logix.git/
  artifacts:
   paths:
    - hash
   when: always
   name: latest
  only:
   variables:
    - $TRIGGER == "automatic"
  script:
   - |+
      git ls-remote "${GIT_URL}" | \
         awk '{ if( $2 == "refs/heads/master" ) { print $1; exit }}' | tee new_hash
      if [ "$(cat new_hash)" != "$(cat hash)" ]; then
         echo "Regenerate pages"
         cp -f new_hash hash
         exit 1
      else
         echo "No need to update pages"
      fi

.pages: &pages
  stage: pages
  image: monachus/hugo
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
   - git status
   - git submodule foreach git pull origin master
   - pushd content
   - git status
   - popd
   - mv ./favicons/* ./content
   - hugo
  artifacts:
    paths:
    - public
    expire_in: 2h
  only:
  - master

pages:
   <<: *pages
   except:
      variables:
       - $TRIGGER == "automatic"

pages:
   <<: *pages
   when: on_failure

