image: monachus/hugo


variables:
  -  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
  - git submodule foreach git pull origin master
  - find || true
  - pushd content
  - ls -larht
  - git status
  - popd
  - hugo -v --debug
  - find || true
  artifacts:
    paths:
    - public
  only:
  - master
