.pages: &pages
  image: monachus/hugo
  variables:
    GIT_SUBMODULE_STRATEGY: none
    GIT_DEPTH: 1
    GIT_CLONE_PATH: /cache
  script:
     - git status
     - rm -rf content
     - git clone https://git.card10.badge.events.ccc.de/card10/logix.git content
     - hugo
  artifacts:
    paths:
      - public
    expire_in: 10m


test pages:
  <<: *pages
  except:
   - master


# Seperated otherwise merge requests would 
# replace the real site
pages:
  <<: *pages
  only:
   - master
