image: monachus/hugo

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
  - git submodule sync --recursive
  - git submodule update --init --recursive --remote --merge
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master
